### PR TITLE
Functions update

### PR DESCRIPTION
**Pull request by marcofugaro**
This PR:

- updates the `color()` function to match the tachyons styleguide
- updates the `color-variants()` function so you can now pass it more color functional classes as childrend. And you don't have to specify the color each time
- adds the `color-states()` function

### CODE REVIEW

**Comment by caesarsol** [comment]
Hey my friend, I am finally here :D 
I would merge this, but the tests are broken. Do you want me to have a look at it and fix?

**Comment by marcofugaro** [comment]
@caesarsol W H A T

Anyway, should be fixed now

**Comment by marcofugaro** [comment]
I had lost every hope

**Comment by caesarsol** [comment]
AHAHAH

**Pull request merged**
